require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ActivosController do

  # This should return the minimal set of attributes required to create a valid
  # Activo. As you add validations to Activo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ActivosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all activos as @activos" do
      activo = Activo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:activos).should eq([activo])
    end
  end

  describe "GET show" do
    it "assigns the requested activo as @activo" do
      activo = Activo.create! valid_attributes
      get :show, {:id => activo.to_param}, valid_session
      assigns(:activo).should eq(activo)
    end
  end

  describe "GET new" do
    it "assigns a new activo as @activo" do
      get :new, {}, valid_session
      assigns(:activo).should be_a_new(Activo)
    end
  end

  describe "GET edit" do
    it "assigns the requested activo as @activo" do
      activo = Activo.create! valid_attributes
      get :edit, {:id => activo.to_param}, valid_session
      assigns(:activo).should eq(activo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Activo" do
        expect {
          post :create, {:activo => valid_attributes}, valid_session
        }.to change(Activo, :count).by(1)
      end

      it "assigns a newly created activo as @activo" do
        post :create, {:activo => valid_attributes}, valid_session
        assigns(:activo).should be_a(Activo)
        assigns(:activo).should be_persisted
      end

      it "redirects to the created activo" do
        post :create, {:activo => valid_attributes}, valid_session
        response.should redirect_to(Activo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved activo as @activo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Activo.any_instance.stub(:save).and_return(false)
        post :create, {:activo => {}}, valid_session
        assigns(:activo).should be_a_new(Activo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Activo.any_instance.stub(:save).and_return(false)
        post :create, {:activo => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested activo" do
        activo = Activo.create! valid_attributes
        # Assuming there are no other activos in the database, this
        # specifies that the Activo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Activo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => activo.to_param, :activo => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested activo as @activo" do
        activo = Activo.create! valid_attributes
        put :update, {:id => activo.to_param, :activo => valid_attributes}, valid_session
        assigns(:activo).should eq(activo)
      end

      it "redirects to the activo" do
        activo = Activo.create! valid_attributes
        put :update, {:id => activo.to_param, :activo => valid_attributes}, valid_session
        response.should redirect_to(activo)
      end
    end

    describe "with invalid params" do
      it "assigns the activo as @activo" do
        activo = Activo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Activo.any_instance.stub(:save).and_return(false)
        put :update, {:id => activo.to_param, :activo => {}}, valid_session
        assigns(:activo).should eq(activo)
      end

      it "re-renders the 'edit' template" do
        activo = Activo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Activo.any_instance.stub(:save).and_return(false)
        put :update, {:id => activo.to_param, :activo => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested activo" do
      activo = Activo.create! valid_attributes
      expect {
        delete :destroy, {:id => activo.to_param}, valid_session
      }.to change(Activo, :count).by(-1)
    end

    it "redirects to the activos list" do
      activo = Activo.create! valid_attributes
      delete :destroy, {:id => activo.to_param}, valid_session
      response.should redirect_to(activos_url)
    end
  end

end
