require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecepcionesActivosController do

  # This should return the minimal set of attributes required to create a valid
  # RecepcionActivo. As you add validations to RecepcionActivo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecepcionesActivosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all recepciones_activos as @recepciones_activos" do
      recepcion_activo = RecepcionActivo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recepciones_activos).should eq([recepcion_activo])
    end
  end

  describe "GET show" do
    it "assigns the requested recepcion_activo as @recepcion_activo" do
      recepcion_activo = RecepcionActivo.create! valid_attributes
      get :show, {:id => recepcion_activo.to_param}, valid_session
      assigns(:recepcion_activo).should eq(recepcion_activo)
    end
  end

  describe "GET new" do
    it "assigns a new recepcion_activo as @recepcion_activo" do
      get :new, {}, valid_session
      assigns(:recepcion_activo).should be_a_new(RecepcionActivo)
    end
  end

  describe "GET edit" do
    it "assigns the requested recepcion_activo as @recepcion_activo" do
      recepcion_activo = RecepcionActivo.create! valid_attributes
      get :edit, {:id => recepcion_activo.to_param}, valid_session
      assigns(:recepcion_activo).should eq(recepcion_activo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RecepcionActivo" do
        expect {
          post :create, {:recepcion_activo => valid_attributes}, valid_session
        }.to change(RecepcionActivo, :count).by(1)
      end

      it "assigns a newly created recepcion_activo as @recepcion_activo" do
        post :create, {:recepcion_activo => valid_attributes}, valid_session
        assigns(:recepcion_activo).should be_a(RecepcionActivo)
        assigns(:recepcion_activo).should be_persisted
      end

      it "redirects to the created recepcion_activo" do
        post :create, {:recepcion_activo => valid_attributes}, valid_session
        response.should redirect_to(RecepcionActivo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recepcion_activo as @recepcion_activo" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecepcionActivo.any_instance.stub(:save).and_return(false)
        post :create, {:recepcion_activo => {}}, valid_session
        assigns(:recepcion_activo).should be_a_new(RecepcionActivo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecepcionActivo.any_instance.stub(:save).and_return(false)
        post :create, {:recepcion_activo => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recepcion_activo" do
        recepcion_activo = RecepcionActivo.create! valid_attributes
        # Assuming there are no other recepciones_activos in the database, this
        # specifies that the RecepcionActivo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RecepcionActivo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => recepcion_activo.to_param, :recepcion_activo => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested recepcion_activo as @recepcion_activo" do
        recepcion_activo = RecepcionActivo.create! valid_attributes
        put :update, {:id => recepcion_activo.to_param, :recepcion_activo => valid_attributes}, valid_session
        assigns(:recepcion_activo).should eq(recepcion_activo)
      end

      it "redirects to the recepcion_activo" do
        recepcion_activo = RecepcionActivo.create! valid_attributes
        put :update, {:id => recepcion_activo.to_param, :recepcion_activo => valid_attributes}, valid_session
        response.should redirect_to(recepcion_activo)
      end
    end

    describe "with invalid params" do
      it "assigns the recepcion_activo as @recepcion_activo" do
        recepcion_activo = RecepcionActivo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecepcionActivo.any_instance.stub(:save).and_return(false)
        put :update, {:id => recepcion_activo.to_param, :recepcion_activo => {}}, valid_session
        assigns(:recepcion_activo).should eq(recepcion_activo)
      end

      it "re-renders the 'edit' template" do
        recepcion_activo = RecepcionActivo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecepcionActivo.any_instance.stub(:save).and_return(false)
        put :update, {:id => recepcion_activo.to_param, :recepcion_activo => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recepcion_activo" do
      recepcion_activo = RecepcionActivo.create! valid_attributes
      expect {
        delete :destroy, {:id => recepcion_activo.to_param}, valid_session
      }.to change(RecepcionActivo, :count).by(-1)
    end

    it "redirects to the recepciones_activos list" do
      recepcion_activo = RecepcionActivo.create! valid_attributes
      delete :destroy, {:id => recepcion_activo.to_param}, valid_session
      response.should redirect_to(recepciones_activos_url)
    end
  end

end
