require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RelacionesArticulosMedidaController do

  # This should return the minimal set of attributes required to create a valid
  # RelacionArticuloMedida. As you add validations to RelacionArticuloMedida, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RelacionesArticulosMedidaController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all relaciones_articulos_medidas as @relaciones_articulos_medidas" do
      relacion_articulo_medida = RelacionArticuloMedida.create! valid_attributes
      get :index, {}, valid_session
      assigns(:relaciones_articulos_medida).should eq([relacion_articulo_medida])
    end
  end

  describe "GET show" do
    it "assigns the requested relacion_articulo_medida as @relacion_articulo_medida" do
      relacion_articulo_medida = RelacionArticuloMedida.create! valid_attributes
      get :show, {:id => relacion_articulo_medida.to_param}, valid_session
      assigns(:relacion_articulo_medida).should eq(relacion_articulo_medida)
    end
  end

  describe "GET new" do
    it "assigns a new relacion_articulo_medida as @relacion_articulo_medida" do
      get :new, {}, valid_session
      assigns(:relacion_articulo_medida).should be_a_new(RelacionArticuloMedida)
    end
  end

  describe "GET edit" do
    it "assigns the requested relacion_articulo_medida as @relacion_articulo_medida" do
      relacion_articulo_medida = RelacionArticuloMedida.create! valid_attributes
      get :edit, {:id => relacion_articulo_medida.to_param}, valid_session
      assigns(:relacion_articulo_medida).should eq(relacion_articulo_medida)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RelacionArticuloMedida" do
        expect {
          post :create, {:relacion_articulo_medida => valid_attributes}, valid_session
        }.to change(RelacionArticuloMedida, :count).by(1)
      end

      it "assigns a newly created relacion_articulo_medida as @relacion_articulo_medida" do
        post :create, {:relacion_articulo_medida => valid_attributes}, valid_session
        assigns(:relacion_articulo_medida).should be_a(RelacionArticuloMedida)
        assigns(:relacion_articulo_medida).should be_persisted
      end

      it "redirects to the created relacion_articulo_medida" do
        post :create, {:relacion_articulo_medida => valid_attributes}, valid_session
        response.should redirect_to(RelacionArticuloMedida.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved relacion_articulo_medida as @relacion_articulo_medida" do
        # Trigger the behavior that occurs when invalid params are submitted
        RelacionArticuloMedida.any_instance.stub(:save).and_return(false)
        post :create, {:relacion_articulo_medida => {}}, valid_session
        assigns(:relacion_articulo_medida).should be_a_new(RelacionArticuloMedida)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RelacionArticuloMedida.any_instance.stub(:save).and_return(false)
        post :create, {:relacion_articulo_medida => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested relacion_articulo_medida" do
        relacion_articulo_medida = RelacionArticuloMedida.create! valid_attributes
        # Assuming there are no other relaciones_articulos_medida in the database, this
        # specifies that the RelacionArticuloMedida created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RelacionArticuloMedida.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => relacion_articulo_medida.to_param, :relacion_articulo_medida => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested relacion_articulo_medida as @relacion_articulo_medida" do
        relacion_articulo_medida = RelacionArticuloMedida.create! valid_attributes
        put :update, {:id => relacion_articulo_medida.to_param, :relacion_articulo_medida => valid_attributes}, valid_session
        assigns(:relacion_articulo_medida).should eq(relacion_articulo_medida)
      end

      it "redirects to the relacion_articulo_medida" do
        relacion_articulo_medida = RelacionArticuloMedida.create! valid_attributes
        put :update, {:id => relacion_articulo_medida.to_param, :relacion_articulo_medida => valid_attributes}, valid_session
        response.should redirect_to(relacion_articulo_medida)
      end
    end

    describe "with invalid params" do
      it "assigns the relacion_articulo_medida as @relacion_articulo_medida" do
        relacion_articulo_medida = RelacionArticuloMedida.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RelacionArticuloMedida.any_instance.stub(:save).and_return(false)
        put :update, {:id => relacion_articulo_medida.to_param, :relacion_articulo_medida => {}}, valid_session
        assigns(:relacion_articulo_medida).should eq(relacion_articulo_medida)
      end

      it "re-renders the 'edit' template" do
        relacion_articulo_medida = RelacionArticuloMedida.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RelacionArticuloMedida.any_instance.stub(:save).and_return(false)
        put :update, {:id => relacion_articulo_medida.to_param, :relacion_articulo_medida => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested relacion_articulo_medida" do
      relacion_articulo_medida = RelacionArticuloMedida.create! valid_attributes
      expect {
        delete :destroy, {:id => relacion_articulo_medida.to_param}, valid_session
      }.to change(RelacionArticuloMedida, :count).by(-1)
    end

    it "redirects to the relaciones_articulos_medida list" do
      relacion_articulo_medida = RelacionArticuloMedida.create! valid_attributes
      delete :destroy, {:id => relacion_articulo_medida.to_param}, valid_session
      response.should redirect_to(relaciones_articulos_medida_url)
    end
  end

end
