require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReparacionesController do

  # This should return the minimal set of attributes required to create a valid
  # Reparacion. As you add validations to Reparacion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReparacionesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all reparaciones as @reparaciones" do
      reparacion = Reparacion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reparaciones).should eq([reparacion])
    end
  end

  describe "GET show" do
    it "assigns the requested reparacion as @reparacion" do
      reparacion = Reparacion.create! valid_attributes
      get :show, {:id => reparacion.to_param}, valid_session
      assigns(:reparacion).should eq(reparacion)
    end
  end

  describe "GET new" do
    it "assigns a new reparacion as @reparacion" do
      get :new, {}, valid_session
      assigns(:reparacion).should be_a_new(Reparacion)
    end
  end

  describe "GET edit" do
    it "assigns the requested reparacion as @reparacion" do
      reparacion = Reparacion.create! valid_attributes
      get :edit, {:id => reparacion.to_param}, valid_session
      assigns(:reparacion).should eq(reparacion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Reparacion" do
        expect {
          post :create, {:reparacion => valid_attributes}, valid_session
        }.to change(Reparacion, :count).by(1)
      end

      it "assigns a newly created reparacion as @reparacion" do
        post :create, {:reparacion => valid_attributes}, valid_session
        assigns(:reparacion).should be_a(Reparacion)
        assigns(:reparacion).should be_persisted
      end

      it "redirects to the created reparacion" do
        post :create, {:reparacion => valid_attributes}, valid_session
        response.should redirect_to(Reparacion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reparacion as @reparacion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reparacion.any_instance.stub(:save).and_return(false)
        post :create, {:reparacion => {}}, valid_session
        assigns(:reparacion).should be_a_new(Reparacion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reparacion.any_instance.stub(:save).and_return(false)
        post :create, {:reparacion => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reparacion" do
        reparacion = Reparacion.create! valid_attributes
        # Assuming there are no other reparaciones in the database, this
        # specifies that the Reparacion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Reparacion.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => reparacion.to_param, :reparacion => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested reparacion as @reparacion" do
        reparacion = Reparacion.create! valid_attributes
        put :update, {:id => reparacion.to_param, :reparacion => valid_attributes}, valid_session
        assigns(:reparacion).should eq(reparacion)
      end

      it "redirects to the reparacion" do
        reparacion = Reparacion.create! valid_attributes
        put :update, {:id => reparacion.to_param, :reparacion => valid_attributes}, valid_session
        response.should redirect_to(reparacion)
      end
    end

    describe "with invalid params" do
      it "assigns the reparacion as @reparacion" do
        reparacion = Reparacion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reparacion.any_instance.stub(:save).and_return(false)
        put :update, {:id => reparacion.to_param, :reparacion => {}}, valid_session
        assigns(:reparacion).should eq(reparacion)
      end

      it "re-renders the 'edit' template" do
        reparacion = Reparacion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reparacion.any_instance.stub(:save).and_return(false)
        put :update, {:id => reparacion.to_param, :reparacion => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reparacion" do
      reparacion = Reparacion.create! valid_attributes
      expect {
        delete :destroy, {:id => reparacion.to_param}, valid_session
      }.to change(Reparacion, :count).by(-1)
    end

    it "redirects to the reparaciones list" do
      reparacion = Reparacion.create! valid_attributes
      delete :destroy, {:id => reparacion.to_param}, valid_session
      response.should redirect_to(reparaciones_url)
    end
  end

end
